### PR TITLE
[ENH] Update topup_eddy subworkflows and eddy module

### PR DESCRIPTION
**Pull request by anroy1**
## Type of improvement

- [ ] Documentation
- [ ] Development tools (e.g. linter, formatter, etc.)
- [ ] Development container
- [ ] Global update (please specify)
- [x] Other (please specify)

## Describe your improvement

subworkflow/topup_eddy:

copy alex's changes for tractoflow

module/preproc/eddy:

- change bval output name: had problem further in the flow caused by lack ox fil extension

## Checklist before requesting a review

- [x] Ensure the syntax is correct (**EditorConfig** and **Prettier** must pass)
- [x] Run the test suites if your changes affect any module
- [x] Regenerate the **Poetry** lock file if you have updated the dependencies
- [x] Ensure the documentation is up-to-date

### CODE REVIEW

**Review by arnaudbore — DISMISSED** [review]
Looks okay but need container version to be updated to 2.0.2 and scilpy version should  not be hardcoded.

**Review by Manonedde — APPROVED** [review]
LGTM !

**Comment by AlexVCaron** [comment]
Closes AlexVCaron/nf-neuro#12

**Comment by AlexVCaron** [comment]
@anroy1 I ended up updateing the branch with the main. It was the reason of a lot of tests triggering for nothing. I did a merge commit, so you should be able to pull if you haven't modified your branch locally since. Else, rebase.

**Comment by AlexVCaron** [comment]
I will add the comments from the joins with remainders in a separate PR

**Review by AlexVCaron — APPROVED** [review]

**Pull request merged**
